const seed = {
  version: APP_CONFIG.VERSION,
  goals2030: [
    { id: "BUSINESS", title: "Business: DFK + INSO as 2026 main goals", currentValue: 0, targetValue: 2, unit: "个主目标", role: "Mainline" },
    { id: "PASSIVE", title: "Passive: remittance system and clients", currentValue: 0, targetValue: 3, unit: "个模块", role: "Mainline", displayTitle: "PASSIVE INCOME" },
    { id: "HEALTH", title: "Keep weight within 72KG ±5KG", currentValue: 24, targetValue: 52, unit: "周", role: "Habit", baselineValue: 24, baselineThrough: "2026-06-11", baseWeightKg: 72, toleranceKg: 5 },
    { id: "MINDSET", title: "Mindset: daily meditation", currentValue: 0, targetValue: 365, unit: "次", role: "Habit", baselineValue: 80 },
    { id: "FAMILY", title: "Girl friend and family life", currentValue: 3, targetValue: 12, unit: "次", role: "Life" },
    { id: "SOCIAL", title: "Meet people and find mentor", currentValue: 1, targetValue: 12, unit: "次", role: "Sideline", displayTitle: "SOCIAL NETWORK" },
    { id: "INTERESTS", title: "Interest trial count", currentValue: 1, targetValue: 3, unit: "次", role: "Sideline" },
    { id: "NEW", title: "AI automation for daily work", currentValue: 0, targetValue: 2, unit: "个自动化", role: "Sideline", displayTitle: "NEW THINGS" }
  ],
  quests: [
    { id: "Q-001", name: "DFK 赚钱", type: "Main", goal: "BUSINESS", target: "每月装柜 30 个", currentValue: 0, targetValue: 30, unit: "柜/月", monthlyMetric: true, description: "每次装柜只记录新增数量；地图自动汇总本月完成比例，历史记录保留用于年末累计。", nextMove: "记录本月新增装柜数量", status: "In Progress", gmn: "G", priority: "High", icon: "🚚" },
    { id: "Q-009", parentQuestId: "Q-001", name: "公司系统维护", type: "Side", goal: "BUSINESS", target: "让公司内部系统、流程、资料和工具稳定运行", description: "处理公司内部系统、打印模板、资料流程和重复问题，形成可复用的稳定做法。", nextMove: "维护一个公司系统或解决一个重复问题", status: "In Progress", gmn: "G", priority: "High", icon: "⚙️" },
    { id: "Q-010", parentQuestId: "Q-001", name: "公司内部管理", type: "Side", goal: "BUSINESS", target: "岗位、责任、交接和内部协作清楚", description: "处理人员、责任分配、交接、检查和内部沟通，让公司日常运作不依赖临时记忆。", nextMove: "整理一个内部责任或交接事项", status: "In Progress", gmn: "M", priority: "Medium", icon: "👥" },
    { id: "Q-016", parentQuestId: "Q-001", name: "客户与物流事务", type: "Side", goal: "BUSINESS", target: "及时处理客户资料回复、物流、单据和交付杂事", description: "集中处理客户信息回复、发货、物流、单据和交付中的临时杂事，避免它们打断主线系统工作。", nextMove: "处理一条客户或物流事务，并记录下一步", status: "In Progress", gmn: "N", priority: "Medium", icon: "📦" },
    { id: "Q-003", name: "INSO 稳定客户收入", type: "Main", goal: "BUSINESS", target: "稳定客户每月收入 10000 RMB", currentValue: 0, targetValue: 10000, unit: "RMB/月", monthlyMetric: true, description: "每次确认收入只记录新增金额；地图自动汇总本月完成比例，历史记录保留用于年末累计。", nextMove: "记录本月新增 INSO 收入", status: "In Progress", gmn: "G", priority: "High", icon: "🔩" },
    { id: "Q-011", parentQuestId: "Q-003", name: "订单跟进", type: "Side", goal: "BUSINESS", target: "订单、RFQ、报价、成交复盘清楚", description: "用于记录所有订单、RFQ、报价、成交相关复盘。每条记录尽量能看出状态、卡点、下一步和成交概率。", nextMove: "复盘一个 RFQ/报价/订单状态并写下一步", status: "In Progress", gmn: "G", priority: "Medium", icon: "💬" },
    { id: "Q-012", parentQuestId: "Q-003", name: "客户开发", type: "Main", goal: "BUSINESS", target: "持续产生新客户线索和有效对话", description: "用于记录新客户开发，包括麦穗、LinkedIn、邮件、Google 搜索等来源。", nextMove: "开发一批新客户，并标记来源和下一步", status: "In Progress", gmn: "G", priority: "High", icon: "📈" },
    { id: "Q-013", parentQuestId: "Q-003", name: "客户维护", type: "Side", goal: "BUSINESS", target: "老客户定期互动和状态观察", description: "用于记录老客户联系、关系维护、定期互动、客户状态观察。", nextMove: "联系一个老客户并记录客户状态", status: "In Progress", gmn: "M", priority: "Medium", icon: "🤝" },
    { id: "Q-002", name: "汇款系统", type: "Main", goal: "PASSIVE", target: "制作流程、稳定客户、开发客户", currentValue: 0, targetValue: 3, unit: "模块", description: "Passive income 先以汇款系统为核心，沉淀流程并形成稳定客户来源。", nextMove: "先把一个汇款流程写成可复用 SOP", status: "Not Started", gmn: "G", priority: "Medium", icon: "🏦" },
    { id: "Q-014", parentQuestId: "Q-002", name: "制作汇款流程", type: "Main", goal: "PASSIVE", target: "汇款流程、资料、费用、限制清楚", description: "把不同通道的流程、费用、到账时间、资料要求和风险点整理成系统。", nextMove: "整理一条完整汇款流程", status: "In Progress", gmn: "G", priority: "Medium", icon: "🧩" },
    { id: "Q-015", parentQuestId: "Q-002", name: "稳定客户", type: "Main", goal: "PASSIVE", target: "让老客户稳定复用汇款服务", description: "维护现有汇款客户，记录频率、需求、问题和下一次跟进。", nextMove: "跟进一个已有汇款客户", status: "Not Started", gmn: "M", priority: "Medium", icon: "🏛️" },
    { id: "Q-020", parentQuestId: "Q-002", name: "开发客户", type: "Main", goal: "PASSIVE", target: "持续开发新的汇款客户", description: "寻找新的汇款客户来源，记录渠道、信任问题和转化动作。", nextMove: "新增一批汇款客户线索", status: "Not Started", gmn: "G", priority: "Medium", icon: "📣" },
    { id: "Q-039", name: "MINDSET", type: "Main", goal: "MINDSET", target: "通过冥想和复盘保持稳定、清醒和行动", description: "MINDSET 的两个独立行动：冥想用于稳定状态，复盘用于整理经验并决定下一步。", nextMove: "选择冥想或复盘，完成一次记录", status: "In Progress", gmn: "G", priority: "Medium", icon: "🧠" },
    { id: "Q-004", parentQuestId: "Q-039", name: "冥想", type: "Habit", goal: "MINDSET", target: "每天完成一次冥想记录", currentValue: 0, targetValue: 365, unit: "次", baselineValue: 80, description: "原来的 smile、read、bad things、心智模型章节和行动都合并到这里，避免冥想完成数据分散。历史未同步冥想次数先补录 80 次，后续自动叠加新记录。", nextMove: "完成 1 次冥想/呼吸/心态记录", status: "In Progress", gmn: "G", priority: "Medium", icon: "🧘" },
    { id: "Q-038", parentQuestId: "Q-039", name: "复盘", type: "Main", goal: "MINDSET", target: "回看真实行动，提炼经验并明确下一步", description: "记录真实发生的事情、发现的问题、有效做法和下一步。复盘记录与冥想次数独立计算。", nextMove: "复盘一个真实场景，写下下一步", status: "In Progress", gmn: "G", priority: "Medium", icon: "🔎" },
    { id: "Q-005", name: "HEALTH", type: "Habit", goal: "HEALTH", target: "全年 52 周体重保持在 72KG ±5KG 范围内", currentValue: 24, targetValue: 52, unit: "周", baselineValue: 24, baselineThrough: "2026-06-11", baseWeightKg: 72, toleranceKg: 5, recordMode: "metric", description: "HEALTH 是结果记录目标，不需要 20 分钟行动。只记录体重；67-77KG 内，本周算达标。2026-06-11 前按已达标 24 周补入基准。", nextMove: "记录本周体重，例如 70.8 KG", status: "In Progress", gmn: "G", priority: "Medium", icon: "💪" },
    { id: "Q-021", name: "GIRL FRIEND", type: "Side", goal: "FAMILY", target: "which plan did she like the most; what experience", currentValue: 3, targetValue: 12, unit: "次", description: "Relationship actions / shared moments can be recorded as Quick Metric or Session depending on real work.", nextMove: "make the plan to China; car fixed", status: "In Progress", gmn: "M", priority: "Medium", icon: "💛" },
    { id: "Q-022", parentQuestId: "Q-021", name: "旅游", type: "Side", goal: "FAMILY", target: "一起计划和完成旅行", description: "旅行作为 girl friend 下面的一个分支，放目的地、预算、时间和行动。", nextMove: "写下一个旅行备选方案", status: "Not Started", gmn: "M", priority: "Low", icon: "🧳" },
    { id: "Q-006", name: "SOCIAL NETWORK", type: "Side", goal: "SOCIAL", target: "认识更多关键人物，并找到导师", description: "记录认识多少人、关键联系人和导师线索。", nextMove: "复盘一个联系人或导师线索", status: "Not Started", gmn: "G", priority: "Medium", icon: "🤝" },
    { id: "Q-007", name: "INTERESTS", type: "Side", goal: "INTERESTS", target: "Interest trial count", currentValue: 1, targetValue: 3, unit: "次", description: "Need define metric type: trial / lesson / hobby session.", nextMove: "记录一次兴趣试验或练习", status: "In Progress", gmn: "M", priority: "Low", icon: "☕" },
    { id: "Q-008", name: "NEW THINGS", type: "Side", goal: "NEW", target: "find things that are fun for life", currentValue: 0, targetValue: 2, unit: "个", description: "Could be Habit if repeated; new experiences/research can be Quick Metric or Session depending on effort.", nextMove: "find things that are fun for life", status: "In Progress", gmn: "G", priority: "High", icon: "✨" },
    { id: "Q-023", parentQuestId: "Q-008", name: "研究 AI 日常工作自动化", type: "Side", goal: "NEW", target: "用 10 个自动化流程支撑 DFK + INSO 每天 4 小时以内", currentValue: 0, targetValue: 10, unit: "个流程", description: "研究 AI 如何嵌入自己的真实工作流，不只学习工具，而是把手动动作变成可复用系统。最终效果是 DFK 每天 ≤2 小时、INSO 每天 ≤2 小时。", nextMove: "列出 DFK 和 INSO 每天最耗时的 5 个动作", status: "In Progress", gmn: "G", priority: "High", icon: "🤖" },
    { id: "Q-024", parentQuestId: "Q-023", name: "快速将工作模式自动化", type: "Main", goal: "NEW", target: "每月至少自动化 1 个重复工作流", description: "把报价、记录、跟进、打印、财务、客户维护等重复动作变成模板、脚本或 AI 工作流。", nextMove: "选一个手动流程，写出输入、处理、输出", status: "In Progress", gmn: "G", priority: "High", icon: "⚙️" },
    { id: "Q-025", parentQuestId: "Q-023", name: "搭建 MVP", type: "Main", goal: "NEW", target: "做出可真实使用的 AI 自动化原型", description: "先做最小可用版本，能节省一次真实手动操作即可，不追求完美。", nextMove: "搭建一个 AI 自动化 MVP 并跑一次真实任务", status: "Not Started", gmn: "G", priority: "High", icon: "🧩" },
    { id: "Q-026", parentQuestId: "Q-023", name: "优化", type: "Main", goal: "NEW", target: "把 MVP 优化到稳定、省时、可重复", description: "记录失败、卡点、误差和节省时间，不断把原型变成稳定工具。", nextMove: "复盘一个 MVP 的卡点并优化一次", status: "Not Started", gmn: "G", priority: "High", icon: "🔧" },
    { id: "Q-027", parentQuestId: "Q-023", name: "可以推销", type: "Side", goal: "NEW", target: "沉淀成可展示、可销售的方案", description: "把自己用出来的 AI 自动化方案整理成案例、演示和报价逻辑，未来可以对外推销。", nextMove: "把一个内部自动化写成客户能听懂的案例", status: "Not Started", gmn: "G", priority: "Medium", icon: "📣" }
  ],
  tasks: [
    { id: "T-001", questId: "Q-009", name: "维护公司系统", instruction: "选择一个公司系统、打印模板、资料流程或重复问题，完成一次维护或修复。", minutes: 20, standard: "完成一个系统维护动作并写清下一步", gmn: "G", skillIds: ["operations", "strategy"], status: "Not Started", quest_type: "side" },
    { id: "T-002", questId: "Q-010", name: "核对财务和制定制度", instruction: "核对本周财务情况，并把发现的问题落实成一条清楚、可检查的公司制度。", minutes: 20, standard: "完成一次财务核对，并写清一条制度的责任、流程和检查方式", gmn: "G", skillIds: ["finance", "operations", "leadership"], status: "Not Started", quest_type: "main" },
    { id: "T-003", questId: "Q-009", name: "更新公司系统记录", instruction: "把公司系统的问题、负责人和下一步集中记录到一个可复盘的位置。", minutes: 20, standard: "完成一次公司系统记录更新", gmn: "G", skillIds: ["operations", "personal-system"], status: "Not Started", quest_type: "side" },
    { id: "T-004", questId: "Q-011", name: "录入所有未处理报价，分配和整理报价", instruction: "把所有未处理报价录入系统，分配责任人并整理当前状态。", minutes: 20, standard: "完成一批未处理报价的录入、分配和整理", gmn: "G", skillIds: ["revenue", "market"], status: "Not Started", quest_type: "side" },
    { id: "T-005", questId: "Q-016", name: "处理客户与物流事务", instruction: "处理一条客户信息回复、物流、单据或交付杂事，并写清下一步。", minutes: 20, standard: "完成一条客户或物流事务处理记录", gmn: "N", skillIds: ["operations", "communication"], status: "Not Started", quest_type: "side" },
    { id: "T-011", questId: "Q-010", name: "更新内部管理记录", instruction: "处理一条岗位、责任、交接或内部协作事项。", minutes: 20, standard: "处理并记录一个内部管理事项", gmn: "M", skillIds: ["operations", "leadership"], status: "Not Started", quest_type: "side" },
    { id: "T-012", questId: "Q-009", name: "检查打印模板", instruction: "检查一个常用单据、标签或交付资料的打印模板。", minutes: 20, standard: "更新一个打印模板或问题记录", gmn: "G", skillIds: ["operations", "personal-system"], status: "Not Started", quest_type: "side" },
    { id: "T-013", questId: "Q-010", name: "写岗位检查标准", instruction: "选择一个岗位或人员协作点，写清责任、检查标准和交接方式。", minutes: 20, standard: "一个岗位/事项的责任清单", gmn: "M", skillIds: ["operations", "leadership"], status: "Not Started", quest_type: "side" },
    { id: "T-014", questId: "Q-011", name: "打开历史报价筛选重点报价", instruction: "打开历史报价记录，筛选重点报价，标记成交可能、卡点和下一步。", minutes: 20, standard: "筛出一批重点报价并写清下一步", gmn: "G", skillIds: ["revenue", "operations"], status: "Not Started", quest_type: "side" },
    { id: "T-015", questId: "Q-011", name: "整理 INSO 订单下一步", instruction: "把正在推进的订单或 RFQ 写清楚当前状态、责任人和下一步。", minutes: 20, standard: "完成一批订单跟进记录", gmn: "G", skillIds: ["revenue", "communication"], status: "Not Started", quest_type: "side" },
    { id: "T-016", questId: "Q-012", name: "快速开发系统", instruction: "用麦穗、LinkedIn、邮件或 Google 搜索快速开发一批客户，并记录来源和下一步。", minutes: 20, standard: "跑完一次可重复的客户开发流程，并产生一批有效客户动作", gmn: "G", skillIds: ["revenue", "market"], status: "Not Started", quest_type: "main" },
    { id: "T-017", questId: "Q-012", name: "打开历史邮件筛选客户并发送", instruction: "打开历史邮件，筛选可继续开发的客户信息，并发送跟进或开发邮件。", minutes: 20, standard: "筛出一批历史客户并完成发送", gmn: "G", skillIds: ["revenue", "communication"], status: "Not Started", quest_type: "main" },
    { id: "T-018", questId: "Q-013", name: "打开客户管理系统选择客户发送信息", instruction: "打开客户管理系统，选择需要维护的客户，发送信息并记录状态。", minutes: 20, standard: "完成一批客户维护信息发送", gmn: "M", skillIds: ["communication", "revenue"], status: "Not Started", quest_type: "side" },
    { id: "T-019", questId: "Q-013", name: "优化客户管理系统", instruction: "优化客户管理系统里的分类、状态、下一步或提醒方式。", minutes: 20, standard: "完成一处客户管理系统优化", gmn: "M", skillIds: ["communication", "personal-system"], status: "Not Started", quest_type: "side" },
    { id: "T-006", questId: "Q-015", name: "跟进汇款稳定客户", instruction: "联系一个已有汇款客户，确认需求、问题和下一次使用可能。", minutes: 20, standard: "完成一个客户跟进记录", gmn: "M", skillIds: ["finance", "communication"], status: "Not Started" },
    { id: "T-020", questId: "Q-014", name: "制作汇款流程", instruction: "整理一个汇款流程的步骤、资料、费用、到账时间和限制。", minutes: 20, standard: "完成一条汇款流程 SOP", gmn: "G", skillIds: ["finance", "operations"], status: "Not Started" },
    { id: "T-021", questId: "Q-014", name: "更新汇款通道规则", instruction: "把一个通道的规则、风险、限制和当前可用状态写清楚。", minutes: 20, standard: "完成一条通道规则更新", gmn: "G", skillIds: ["finance", "operations"], status: "Not Started" },
    { id: "T-022", questId: "Q-020", name: "开发汇款客户", instruction: "寻找一批新的汇款客户线索，并记录来源、信任问题和下一步。", minutes: 20, standard: "新增一批汇款客户线索", gmn: "G", skillIds: ["finance", "communication"], status: "Not Started" },
    { id: "T-023", questId: "Q-009", name: "测试打印流程", instruction: "从数据到打印成品走一遍，记录卡点和修复动作。", minutes: 20, standard: "完成一次打印流程测试", gmn: "G", skillIds: ["operations", "personal-system"], status: "Not Started" },
    { id: "T-024", questId: "Q-010", name: "整理人员交接", instruction: "整理一个人员交接事项：输入、输出、责任人和检查方式。", minutes: 20, standard: "完成一条交接标准", gmn: "M", skillIds: ["operations", "leadership"], status: "Not Started" },
    { id: "T-025", questId: "Q-016", name: "整理客户与物流清单", instruction: "整理一批待回复客户信息、物流、单据或交付事项，并标记下一步。", minutes: 20, standard: "完成一份客户与物流处理清单", gmn: "N", skillIds: ["operations", "communication"], status: "Not Started" },
    { id: "T-026", questId: "Q-021", name: "关系维护记录", instruction: "记录一次沟通、约会、计划或需要注意的关系细节。", minutes: 20, standard: "完成一条 girl friend 关系记录", gmn: "M", skillIds: ["communication", "personal-system"], status: "Not Started" },
    { id: "T-027", questId: "Q-022", name: "旅行备选方案", instruction: "写一个旅行目的地、预算、时间和下一步动作。", minutes: 20, standard: "完成一个旅行备选方案", gmn: "M", skillIds: ["communication", "personal-system"], status: "Not Started" },
    { id: "T-028", questId: "Q-008", name: "记录 AI 自动化机会", instruction: "写下一个每天重复、耗时、适合 AI 化的工作动作。", minutes: 20, standard: "完成一个自动化机会记录", gmn: "G", skillIds: ["strategy", "operations"], status: "Not Started" },
    { id: "T-029", questId: "Q-024", name: "拆一个手动工作流", instruction: "选择一个 DFK 或 INSO 手动流程，写出输入、处理、输出、耗时和卡点。", minutes: 20, standard: "一条可自动化流程清单", gmn: "G", skillIds: ["operations", "strategy"], status: "Not Started" },
    { id: "T-030", questId: "Q-025", name: "搭建 AI 自动化 MVP", instruction: "用最简单方式做一个能跑通真实任务的 AI 自动化原型。", minutes: 20, standard: "MVP 跑通一次真实任务", gmn: "G", skillIds: ["operations", "market"], status: "Not Started" },
    { id: "T-031", questId: "Q-026", name: "优化自动化流程", instruction: "复盘一个 AI 自动化 MVP 的错误、卡点、耗时和下一步优化。", minutes: 20, standard: "完成一次优化记录或修正", gmn: "G", skillIds: ["operations", "personal-system"], status: "Not Started" },
    { id: "T-032", questId: "Q-027", name: "整理可推销案例", instruction: "把一个内部 AI 自动化方案写成客户能懂的案例：问题、方案、效果、报价方向。", minutes: 20, standard: "完成一版案例草稿", gmn: "G", skillIds: ["communication", "market"], status: "Not Started" },
    { id: "T-007", questId: "Q-004", name: "每日冥想记录", instruction: "冥想/呼吸后描述场景、身体、情绪和念头。原来的 MINDSET 行动都合并到这张卡。", minutes: 10, standard: "完成一次冥想记录", gmn: "G", skillIds: ["personal-system"], status: "Not Started", quest_type: "main" },
    { id: "T-041", questId: "Q-038", name: "复盘一次真实行动", instruction: "回看一个真实场景：发生了什么、卡在哪里、什么有效，以及下一步做什么。", minutes: 20, standard: "完成一次复盘并写清下一步", gmn: "G", skillIds: ["personal-system", "strategy"], status: "Not Started", quest_type: "main" },
    { id: "T-008", questId: "Q-005", name: "每周体重测量", instruction: "记录本周体重、变化原因、饮食/运动状态。", minutes: 10, standard: "完成一次体重趋势记录", gmn: "G", skillIds: ["personal-system"], status: "Not Started", recordMode: "metric" },
    { id: "T-009", questId: "Q-006", name: "复盘一个联系人", instruction: "写下一个人能帮什么、你能提供什么、下一步联系。", minutes: 20, standard: "完成联系人卡片", gmn: "G", skillIds: ["communication", "leadership"], status: "Not Started" },
    { id: "T-010", questId: "Q-007", name: "V60/兴趣记录", instruction: "记录一次咖啡/运动体验和改进点。", minutes: 20, standard: "完成一条兴趣日志", gmn: "M", skillIds: ["personal-system"], status: "Not Started" },
    { id: "T-RND-001", questId: "Q-011", name: "紧急回复重要客户 RFQ", instruction: "突发客户请求，快速判断是否值得推进。", minutes: 20, standard: "完成判断并记录下一步", gmn: "G", skillIds: ["revenue", "communication"], status: "Not Started", is_random_event: true, quest_type: "main", estimated_sessions: 1, reason: "重要客户临时询价，可能影响元器件业务收入。", source: "emergency", linked_goal_id: "BUSINESS", priority: "urgent", pivot_status: "none", original_title: "紧急回复重要客户 RFQ", current_title: "紧急回复重要客户 RFQ", pivot_reason: "", discovery_note: "", generated_task_id: "" }
  ],
  skills: [
    { id: "strategy", name: "Strategy / 战略判断", level: 1, xp: 35, maxXp: 100, description: "把长期方向翻译成目标、取舍、优先级和执行路线。", requirements: ["Define and execute long-term strategy", "Translate strategy into measurable operating plans"], unlock: "战略 memo 模板" },
    { id: "revenue", name: "Revenue / 增长与销售", level: 1, xp: 20, maxXp: 100, description: "客户开发、GTM、销售流程、渠道和 pipeline。", requirements: ["Own revenue generation", "Build sales playbook and customer acquisition strategy"], unlock: "客户开发地图" },
    { id: "finance", name: "Finance / 财务与资本", level: 1, xp: 12, maxXp: 100, description: "现金流、预算、财务模型、融资和银行/投资人沟通。", requirements: ["Lead capital raising", "Financial planning and scenario analysis"], unlock: "现金流仪表盘" },
    { id: "operations", name: "Operations / 运营系统", level: 1, xp: 42, maxXp: 100, description: "SOP、KPI、流程优化、跨部门协同。", requirements: ["Build scalable operating model", "Monitor KPIs and remove bottlenecks"], unlock: "SOP 任务工坊" },
    { id: "leadership", name: "Leadership / 团队领导", level: 1, xp: 16, maxXp: 100, description: "组织设计、招聘、绩效、沟通、责任感。", requirements: ["Build and lead high-caliber teams", "Create accountability and alignment"], unlock: "团队任务面板" },
    { id: "communication", name: "Communication / 影响力表达", level: 1, xp: 25, maxXp: 100, description: "pitch、决策文档、board update、LinkedIn 内容。", requirements: ["Serve as external face", "Write strategic memos and investor updates"], unlock: "Pitch 训练场" },
    { id: "market", name: "Market Insight / 市场洞察", level: 1, xp: 18, maxXp: 100, description: "竞品、客户需求、行业趋势、市场进入。", requirements: ["Market entry and partnerships", "Use customer and market data for decisions"], unlock: "市场侦察地图" },
    { id: "personal-system", name: "Personal System / 自我系统", level: 2, xp: 65, maxXp: 120, description: "精力、专注、GMN 判断、复盘、稳定执行。", requirements: ["Prioritize what gets done now vs later", "Unblock execution and follow-through"], unlock: "AI 周复盘" }
  ],
  logs: [
    { id: "L-001", date: "2026-05-10", minutes: 20, gmn: "G", questId: "Q-009", taskId: "T-001", whatDone: "梳理 DFK 当前系统问题", problem: "报价、客户、订单记录分散，复盘成本高", solution: "先集中记录关键流程和卡点", good: "找到了业务系统问题", bad: "流程还不够统一", nextStep: "优化报价和订单流程", skillXp: [{ skillId: "operations", xp: 30 }, { skillId: "strategy", xp: 10 }] },
    { id: "L-002", date: "2026-05-10", minutes: 20, gmn: "G", questId: "Q-009", taskId: "T-002", whatDone: "整理报价和订单流程", problem: "不同客户跟进方式不一致", solution: "先写出标准动作", good: "流程更清楚", bad: "还需要真实订单测试", nextStep: "调整 DFK 业务记录方式", skillXp: [{ skillId: "operations", xp: 30 }, { skillId: "revenue", xp: 10 }] },
    { id: "L-003", date: "2026-05-10", minutes: 10, gmn: "M", questId: "Q-004", taskId: "T-007", whatDone: "安静坐下，做了一次短冥想", problem: "呼吸慢下来后，焦虑感有下降", solution: "", good: "", bad: "", nextStep: "每天做一次短记录", skillXp: [{ skillId: "personal-system", xp: 15 }], is_pivoted: false, original_task_id: "T-007", actual_task_id: "T-007", pivot_note: "" },
    { id: "L-004", date: "2026-05-10", minutes: 20, gmn: "G", questId: "Q-011", taskId: "T-RND-001", whatDone: "处理客户临时 RFQ，并判断为可推进机会", problem: "规格信息不完整", solution: "先回确认清单", good: "没有把突发事件当成打乱计划，而是归入 main/G", bad: "", nextStep: "等待客户补规格后报价", skillXp: [{ skillId: "revenue", xp: 30 }, { skillId: "communication", xp: 10 }], is_random_event: true, is_pivoted: false, original_task_id: "T-RND-001", actual_task_id: "T-RND-001", pivot_note: "" }
  ],
  metricLogs: [],
  todos: [],
  model: [
    ["5-Year", "2030 Goal", "长期方向/人生地图", "Goal ID, 2030 target, unit, achieved, description", "决定哪些时间算真实成长"],
    ["Annual", "2026 Goal/KR", "今年关键结果", "Goal ID, Type, target, current, Next Move", "把长期目标落到今年"],
    ["Weekly", "Quest", "本周主线/支线", "Quest ID, linked goal, objective, next move, GMN default", "像游戏关卡一样推进"],
    ["Session", "20min Task", "一次可启动小战斗", "Task ID, output standard, skillIds", "降低启动成本，并映射到技能 XP"],
    ["Log", "Session Log", "真实执行过程记录", "GMN, content, problem, solution, good/bad, next action", "为周复盘和 AI 分析提供数据"],
    ["Log", "Metric Log", "可累计的数据记录", "date, month, metricType, value, unit", "DFK 装柜和 INSO 收入按月汇总，历史可用于全年累计"],
    ["Skill", "CEO Skill", "专项能力成长", "skillId, level, xp, requirements, unlock", "把执行任务转化成长期职业技能"],
    ["Review", "Weekly Review", "复盘并生成下周路线", "G/M/N占比、输出、问题、下一步", "形成计划-执行-复盘闭环"],
    ["Inbox", "Todo", "极简待办", "category, content, is_starred, is_urgent, status, completed_at", "自动同步到 Google Sheet，快速记录、优先处理、保留完成历史"],
    ["Dynamic", "Random Event", "突发任务收编", "quest_type, gmn_type, source, reason, priority", "把临时事件判断为机会、风险、维护或噪音"],
    ["Dynamic", "Task Pivot", "任务转向轨迹", "pivot_status, original_task_id, actual_task_id, pivot_note", "保留探索过程，不覆盖历史"]
  ]
};
